### PR TITLE
DEV: Update minimum requirement to python 3.7

### PR DESCRIPTION
**Pull request by shaneahmed**
- Drop support for python 3.6
- Update minimum requirement to python 3.7
- Add support for python 3.9

### CODE REVIEW

**Review by John-P — APPROVED** [review]
Looking good too me! :+1: Thank you for sorting out this PR.

**Comment by mostafajahanifar** [comment]
Dear @shaneahmed 
I have tried to install this branch on a new conda environment with Python 3.9 installed, using the following command:
```
pip install git+https://github.com/TIA-Lab/tiatoolbox@dev-python36to39
```
but it failed to compile scikit-learn. It seemed to me it was because of the pin on the scikit-learn version which cause the build using pip to fail. However, I was able to install scikit-learn==0.23.2 using `conda install` command (it was able to resolve the dependencies and the build issues). So, it seems that with this PR, installation through Conda would be OK while installing from scratch using pip would raise a chain of errors.
Also, it seems that `requests` package should be added to the requirements.

In any case, after I finished installing the `tiatoolbox` using a combination `conda install` and `pip`, when I tried to import the toolbox in python 3.9, the following error came up:
```
>>> import tiatoolbox
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```
I'm not sure if this is related to the installation or my laptop config, so I need to investigate it in more depth later.

**Review by mostafajahanifar — CHANGES_REQUESTED** [review]
Dear @shaneahmed 
I have tried to install this branch on a new conda environment with Python 3.9 installed, using the following command:
```
pip install git+https://github.com/TIA-Lab/tiatoolbox@dev-python36to39
```
but it failed to compile scikit-learn. It seemed to me it was because of the pin on the scikit-learn version which cause the build using pip to fail. However, I was able to install scikit-learn==0.23.2 using `conda install` command (it was able to resolve the dependencies and the build issues). So, it seems that with this PR, installation through Conda would be OK while installing from scratch using pip would raise a chain of errors.
Also, it seems that `requests` package should be added to the requirements.

In any case, after I finished installing the `tiatoolbox` using a combination `conda install` and `pip`, when I tried to import the toolbox in python 3.9, the following error came up:
```
>>> import tiatoolbox
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```
I'm not sure if this is related to the installation or my laptop config, so I need to investigate it in more depth later.

**Comment by shaneahmed** [comment]
> Dear @shaneahmed
> I have tried to install this branch on a new conda environment with Python 3.9 installed, using the following command:
> 
> ```
> pip install git+https://github.com/TIA-Lab/tiatoolbox@dev-python36to39
> ```
> 
> but it failed to compile scikit-learn. It seemed to me it was because of the pin on the scikit-learn version which cause the build using pip to fail. However, I was able to install scikit-learn==0.23.2 using `conda install` command (it was able to resolve the dependencies and the build issues). So, it seems that with this PR, installation through Conda would be OK while installing from scratch using pip would raise a chain of errors.
> Also, it seems that `requests` package should be added to the requirements.
> 
> In any case, after I finished installing the `tiatoolbox` using a combination `conda install` and `pip`, when I tried to import the toolbox in python 3.9, the following error came up:
> 
> ```
> >>> import tiatoolbox
> OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
> ```
> 
> I'm not sure if this is related to the installation or my laptop config, so I need to investigate it in more depth later.

@mostafajahanifar please can you try again now? I have updated `scikit-learn==0.23.2` to `scikit-learn>=0.23.2`. @simongraham  are you ok with this change?

**Comment by mostafajahanifar** [comment]
> @mostafajahanifar please can you try again now? I have updated `scikit-learn==0.23.2` to `scikit-learn>=0.23.2`. 

Now pip can successfully build all the libraries. However, `requests` package is still missing from the requirement. When I install that package myself, I was able to successfully run `import tiatoolbox`

**Review by vqdang — APPROVED** [review]

**Comment by vqdang** [comment]
As this passes all tests. I don't think there would be obvious problems. However, sklearn has some breaking changes between 0.24 and 0.23. We don't use the affected functionalities at the moment but I think we may need to pin to sklearn to either 0.23 or 0.24.

**Review by mostafajahanifar — APPROVED** [review]
It seems that this PR is ready to be merged. Thanks @shaneahmed for doing it. Just member to include `requests` package in the requirements before merging, please.

**Pull request merged**
