### PR TITLE
DOC: update example_stainnorm.ipynb

### PR DESCRIPTION
**Pull request by DavidBAEpstein**
Introductory markdown cell explaining why normalising stain can be a good idea.
Copied several cells from example_wsiread.ipynb. It's a pity that there isn't (or I can't find) any mechanism for sharing cells that are identical in example_wsiread.ipynb and example_stainnorm.ipynb. This makes maintenance more difficult. One of the common cells is an initial cell in bash, banishing error messages and warning messages that previously occurred even when the user used the jupyter notebook correctly.
I changed "normalize" to "normalise", and similarly for related words like "normalisation", which is the spelling adopted previously in the stainnorm module.
I changed an erroneous "objective power x16" to the correct "objective power x20" in one markdown cell.
In general, I made markdown cells somewhat shorter, more informative, clearer and used better English style.
Having read a bit about Unit Tests, it doesn't seem to me that there are any appropriate tests, but I would like to see what the robot says about code coverage.
Remaining tasks ( I need to research these) are: 
1) set up pre-commit hooks
2) (try to) get Kaggle versions of the notebooks to work as expected.

### CODE REVIEW

**Comment by DavidBAEpstein** [comment]
Dear Shan,
Can you tell me what I should do about the two example notebooks that you assigned to me?
They need to be merged with develop. Maybe you want me to request particular reviewers, but I have no idea who has time to do the reviewing—everything seems very hectic at the moment.

There are some minor improvements that could be done, which I haven’t done, like making the Kaggle badge useful. But I’m busy preparing slides for the
Survival Patari, so I think the notebooks are fine to go ahead in their present form.

I’m reluctant to merge these my branches with develop on my own, because I feel I don’t have enough experience with Github. I could mess things up just before the Master Classes.

Best wishes
David





On 4 May 2021, at 17:32, Shan E Ahmed Raza ***@***.******@***.***>> wrote:



Assigned #94<https://github.com/TIA-Lab/tiatoolbox/pull/94> to @DavidBAEpstein<https://github.com/DavidBAEpstein>.

**Review by shaneahmed — CHANGES_REQUESTED** [review]
Thanks @DavidBAEpstein for your work on example notebooks.
I have added my comments here https://app.reviewnb.com/TIA-Lab/tiatoolbox/pull/94/

**Comment by DavidBAEpstein** [comment]
A careful text cell is needed. We should not suggest in the notebook that people should run “pip install tiatoolbox” if not in Colab. Our old version of numpy would overwrite their new and better version of numpy. Some Python program that used to work perfectly suddenly stops working as a result of attending the Masterclass. Is psycholoogical counselling provided as part of Masterclass?😀

Best wishes
David

On 13 May 2021, at 10:45, Shan E Ahmed Raza ***@***.******@***.***>> wrote:



apt-get is a ubuntu built in command not just colab.

But I guess let's split the two just to clarify that these commands are just for colab conflicts and these are for installing tiatoolbox as you have mentioned in the stainnorm example.

________________________________

View entire conversation<https://app.reviewnb.com/TIA-Lab/tiatoolbox/pull/94/discussion/> on ReviewNB

**Comment by DavidBAEpstein** [comment]
Hi David,

Best practice to always install packages for a single project in virtual
environments. That's the beauty of python. Also pip install doesn't
automatically overwrite existing packages if the requirement is met.
However, the users can force install latest packages using --upgrade or
--ignore-installed flags. So there is no danger here. Also running these
notebooks on colab will not harm anyone's python environment.

Kind regards,
Shan E Ahmed Raza

**Comment by DavidBAEpstein** [comment]
"Our old version of numpy would overwrite their new and better version of
numpy. "

Just to clarify, tiatoolbox does not require an old version of numpy. It
just requires numpy and by default the latest version is installed. As I
mentioned in my previous email, there was one of the recent versions of
numpy with a bug which was fixed by numpy developers in the latest version.
So we had pinned numpy to avoid installation of that version only. In the
current setting, tiatoolbox installs the latest version by default.

Best,
Shan E Ahmed Raza

**Review by shaneahmed — COMMENTED** [review]
Thanks @DavidBAEpstein 
There are a few typos in `examples/01_example_wsiread.ipynb`. Please can you resolve these and I will then approve this PR.

**Pull request merged**
